/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_js_bindings.py -c system_jsb.ini" on 2012-12-17
* Script version: v0.5
*/
#include "js_bindings_config.h"
#include "jsapi.h"

#ifdef __cplusplus
extern "C" {
#endif
bool JSB_preloadSource(JSContext *cx, uint32_t argc, jsval *vp);
void jsb_register_preloadSource( JSContext *globalC, JSObject *globalO);
#ifdef __cplusplus
}
#endif


//#endif // JSB_INCLUDE_SYSTEM
